package com.codeoftheweb.salvo;

import org.springframework.boot.CommandLineRunner;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.Bean;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.RestController;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

@SpringBootApplication
public class SalvoApplication {

	public static void main(String[] args) {
		SpringApplication.run(SalvoApplication.class, args);
	}
	@Bean
	public CommandLineRunner initData(PlayerRepository playerRepository, GameRepository gameRepository, GamePlayerRepository gamePlayerRepository, ShipRepository shipRepository) {
		return (args) -> {
			Player p1 = new Player("j.bauer@ctu.gov");
			Player p2 = new Player("c.obrian@ctu.gov");
			Player p3 = new Player("kim_bauer@gmail.com");
			Player p4 = new Player("t.almeida@ctu.gov");
			Player p5 = new Player("rodarg@gmail.com");
			playerRepository.save(p1);
			playerRepository.save(p2);
			playerRepository.save(p3);
			playerRepository.save(p4);
			playerRepository.save(p5);
			Date date =new Date();
			Date date2 = Date.from(date.toInstant().plusSeconds(3600));
			Date date3 = Date.from(date2.toInstant().plusSeconds(3600));
			Game g1 = new Game(date);
			Game g2 = new Game(date2);
			Game g3 = new Game(date3);
			Game g4 = new Game(date);
			Game g5 = new Game(date);
			Game g6 = new Game(date);
			Game g7 = new Game(date);
			Game g8 = new Game(date);
			gameRepository.save(g1);
			gameRepository.save(g2);
			gameRepository.save(g3);
			gameRepository.save(g4);
			gameRepository.save(g5);
			gameRepository.save(g6);
			gameRepository.save(g7);
			gameRepository.save(g8);
			GamePlayer gp1 = new GamePlayer(date, p1, g1);
			GamePlayer gp2 = new GamePlayer(date, p2, g1);
			GamePlayer gp3 = new GamePlayer(date, p1, g2);
			GamePlayer gp4 = new GamePlayer(date, p2, g2);
			GamePlayer gp5 = new GamePlayer(date, p2, g3);
			GamePlayer gp6 = new GamePlayer(date, p4, g3);
			GamePlayer gp7 = new GamePlayer(date, p2, g4);
			GamePlayer gp8 = new GamePlayer(date, p1, g4);
			GamePlayer gp9 = new GamePlayer(date, p4, g5);
			GamePlayer gp10 = new GamePlayer(date, p1, g5);
			GamePlayer gp11 = new GamePlayer(date, p3, g6);
			GamePlayer gp12 = new GamePlayer(date, p4, g7);
			GamePlayer gp13 = new GamePlayer(date, p3, g8);
			GamePlayer gp14 = new GamePlayer(date, p4, g8);
			gamePlayerRepository.save(gp1);
			gamePlayerRepository.save(gp2);
			gamePlayerRepository.save(gp3);
			gamePlayerRepository.save(gp4);
			gamePlayerRepository.save(gp5);
			gamePlayerRepository.save(gp6);
			gamePlayerRepository.save(gp7);
			gamePlayerRepository.save(gp8);
			gamePlayerRepository.save(gp9);
			gamePlayerRepository.save(gp10);
			gamePlayerRepository.save(gp11);
			gamePlayerRepository.save(gp12);
			gamePlayerRepository.save(gp13);
			gamePlayerRepository.save(gp14);
			Set <String> location1 = new HashSet<String>();
			location1.add("H2");
			location1.add("H3");
			location1.add("H4");
			Ship s1 = new Ship("Destroyer",gp1,location1 );
			Set <String> location2 = new HashSet<String>();
			location2.add("E1");
			location2.add("F1");
			location2.add("G1");
			Ship s2 = new Ship("Submarine",gp1,location2 );
			Set <String> location3 = new HashSet<String>();
			location3.add("B4");
			location3.add("B5");
			Ship s3 = new Ship("Destroyer",gp1,location3 );
			Set <String> location4 = new HashSet<String>();
			location4.add("B5");
			location4.add("C5");
			location4.add("D5");
			Ship s4 = new Ship("Destroyer",gp1,location4 );
			Set <String> location5 = new HashSet<String>();
			location5.add("F1");
			location5.add("F2");
			Ship s5 = new Ship("Patrol Boat",gp1,location5 );
			Set <String> location6 = new HashSet<String>();
			location6.add("B5");
			location6.add("C5");
			location6.add("D5");
			Ship s6 = new Ship("Destroyer",gp2,location6 );
			Set <String> location7 = new HashSet<String>();
			location7.add("C6");
			location7.add("C7");
			Ship s7 = new Ship("Patrol Boat",gp2,location7 );
			Set <String> location8 = new HashSet<String>();
			location8.add("A2");
			location8.add("A3");
			location8.add("A4");
			Ship s8 = new Ship("Submarine",gp2,location8 );
			Set <String> location9 = new HashSet<String>();
			location9.add("G6");
			location9.add("H6");
			Ship s9 = new Ship("Patrol Boat",gp2,location9);
			Set <String> location10 = new HashSet<String>();
			location10.add("B5");
			location10.add("C5");
			location10.add("D5");
			Ship s10 = new Ship("Destroyer",gp3,location10 );
			Set <String> location11 = new HashSet<String>();
			location11.add("C6");
			location11.add("C7");
			Ship s11 = new Ship("Patrol Boat",gp3,location11 );
			Set <String> location12 = new HashSet<String>();
			location12.add("A2");
			location12.add("A3");
			location12.add("A4");
			Ship s12 = new Ship("Submarine",gp3,location12 );
			Set <String> location13 = new HashSet<String>();
			location13.add("G6");
			location13.add("H6");
			Ship s13 = new Ship("Patrol Boat",gp3,location13 );
			Set <String> location14 = new HashSet<String>();
			location14.add("B5");
			location14.add("C5");
			location14.add("D5");
			Ship s14 = new Ship("Destroyer",gp4,location14 );
			Set <String> location15= new HashSet<String>();
			location15.add("C6");
			location15.add("C7");
			Ship s15 = new Ship("Patrol Boat",gp4,location15 );
			Set <String> location16= new HashSet<String>();
			location16.add("A2");
			location16.add("A3");
			location16.add("A4");
			Ship s16 = new Ship("Submarine",gp4,location16 );
			Set <String> location17 = new HashSet<String>();
			location17.add("G6");
			location17.add("H6");
			Ship s17 = new Ship("Patrol Boat",gp4,location17 );
			Set <String> location18 = new HashSet<String>();
			location18.add("B5");
			location18.add("C5");
			location18.add("D5");
			Ship s18 = new Ship("Destroyer",gp5,location18 );
			Set <String> location19= new HashSet<String>();
			location19.add("C6");
			location19.add("C7");
			Ship s19 = new Ship("Patrol Boat",gp5,location19 );
			Set <String> location20= new HashSet<String>();
			location20.add("A2");
			location20.add("A3");
			location20.add("A4");
			Ship s20 = new Ship("Submarine",gp5,location20);
			Set <String> location21 = new HashSet<String>();
			location21.add("G6");
			location21.add("H6");
			Ship s21 = new Ship("Patrol Boat",gp5,location21 );
			Set <String> location22 = new HashSet<String>();
			location22.add("B5");
			location22.add("C5");
			location22.add("D5");
			Ship s22 = new Ship("Destroyer",gp6,location22 );
			Set <String> location23= new HashSet<String>();
			location23.add("C6");
			location23.add("C7");
			Ship s23 = new Ship("Patrol Boat",gp6,location23 );
			Set <String> location24= new HashSet<String>();
			location24.add("B5");
			location24.add("C5");
			location24.add("D5");
			Ship s24 = new Ship("Destroyer",gp8,location24 );
			Set <String> location25 = new HashSet<String>();
			location25.add("C6");
			location25.add("C7");
			Ship s25 = new Ship("Patrol Boat",gp8,location25 );
			Set <String> location26= new HashSet<String>();
			location26.add("A2");
			location26.add("A3");
			location26.add("A4");
			Ship s26 = new Ship("Submarine",gp8,location26 );
			Set <String> location27 = new HashSet<String>();
			location27.add("G6");
			location27.add("H6");
			Ship s27 = new Ship("Patrol Boat",gp8,location27 );
			shipRepository.save(s1);
			shipRepository.save(s2);
			shipRepository.save(s3);
			shipRepository.save(s4);
			shipRepository.save(s5);
			shipRepository.save(s6);
			shipRepository.save(s7);
			shipRepository.save(s8);
			shipRepository.save(s9);
			shipRepository.save(s10);
			shipRepository.save(s11);
			shipRepository.save(s12);
			shipRepository.save(s13);
			shipRepository.save(s14);
			shipRepository.save(s15);
			shipRepository.save(s16);
			shipRepository.save(s17);
			shipRepository.save(s18);
			shipRepository.save(s20);
			shipRepository.save(s21);
			shipRepository.save(s22);
			shipRepository.save(s23);
			shipRepository.save(s24);
			shipRepository.save(s25);
			shipRepository.save(s26);
			shipRepository.save(s27);
		};
	}

}
